apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: containers-capstone
  namespace: containers-learning
spec:
  ingressClassName: nginx
  rules:
    - host: containers-capstone.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: containers-capstone
                port:
                  number: 80
