(ns openapi-codegen.generator
  "Generate Malli schema definition files from parsed OpenAPI schema maps."
  (:require [clojure.string :as str]))

(defn openapi-type->malli
  "Map an OpenAPI type string (with optional items map) to a Malli type form.

  Mapping:
    string  -> :string
    integer -> :int
    number  -> number?
    boolean -> :boolean
    array   -> [:vector <item-type>]   (item-type resolved recursively)
    object  -> :map
    other   -> :any"
  ([openapi-type]
   (openapi-type->malli openapi-type nil))
  ([openapi-type items]
   (case openapi-type
     "string"  :string
     "integer" :int
     "number"  'number?
     "boolean" :boolean
     "array"   (let [item-type (if items
                                 (openapi-type->malli (get items "type" "string") (get items "items"))
                                 :any)]
                 [:vector item-type])
     "object"  :map
     :any)))

(defn- property->malli-entry
  "Convert a parsed property map to a Malli schema entry vector.

  Required properties  -> [:prop-keyword malli-type]
  Optional properties  -> [:prop-keyword {:optional true} malli-type]"
  [{:keys [name required? type items]}]
  (let [kw         (keyword name)
        malli-type (openapi-type->malli type items)]
    (if required?
      [kw malli-type]
      [kw {:optional true} malli-type])))

(defn schema->malli
  "Convert a parsed schema map to a Malli [:map ...] form."
  [{:keys [properties]}]
  (into [:map] (mapv property->malli-entry properties)))

(defn- schema-name->ns-name
  "Convert a PascalCase schema name to a kebab-case namespace segment.

  Examples:
    LoginRequest    -> login-request
    PLReport        -> p-l-report
    JwkKey          -> jwk-key"
  [schema-name]
  (-> schema-name
      (str/replace #"([A-Z]+)([A-Z][a-z])" "$1-$2")
      (str/replace #"([a-z\d])([A-Z])" "$1-$2")
      str/lower-case))

(defn- schema->clj-source
  "Render a single schema as a Clojure source string.

  Generates:
    - A namespace declaration (openapi-codegen.schemas.<kebab-name>)
    - A DO NOT EDIT header comment
    - A `schema` def containing the Malli [:map ...] form"
  [{:keys [name description] :as parsed-schema}]
  (let [ns-segment  (schema-name->ns-name name)
        ns-name     (str "openapi-codegen.schemas." ns-segment)
        malli-form  (schema->malli parsed-schema)
        desc-comment (when description (str "\n;; " description "\n"))]
    (str ";; DO NOT EDIT — generated by openapi-codegen from OpenAPI spec\n"
         desc-comment
         "(ns " ns-name "\n"
         "  (:require [malli.core :as m]))\n\n"
         "(def schema\n"
         "  " (pr-str malli-form) ")\n")))

(defn- ns-segment->file-segment
  "Convert a kebab-case namespace segment to an underscore file segment.

  Clojure namespace `openapi-codegen.schemas.login-request` maps to
  file path `openapi_codegen/schemas/login_request.clj`."
  [ns-segment]
  (str/replace ns-segment "-" "_"))

(defn generate-schema-files
  "For each parsed schema in schemas, write a .clj file to output-dir.

  Files are written at the correct Clojure namespace path:
  output-dir/openapi_codegen/schemas/<underscore_name>.clj
  Returns a sequence of written file paths."
  [schemas output-dir]
  (let [schema-dir (str output-dir "/openapi_codegen/schemas")
        dir        (java.io.File. schema-dir)]
    (.mkdirs dir)
    (mapv (fn [parsed-schema]
            (let [ns-segment    (schema-name->ns-name (:name parsed-schema))
                  file-segment  (ns-segment->file-segment ns-segment)
                  file-name     (str file-segment ".clj")
                  file-path     (str schema-dir "/" file-name)
                  source        (schema->clj-source parsed-schema)]
              (spit file-path source)
              file-path))
          schemas)))
