//go:build integration

package cmd

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/cucumber/godog"
	"github.com/wahidyankf/ose-public/apps/rhino-cli/internal/envbackup"
)

var specsIntEnvBackupDir = func() string {
	_, f, _, _ := runtime.Caller(0)
	return filepath.Join(filepath.Dir(f), "../../../specs/apps/rhino/cli/gherkin")
}()

type envBackupIntSteps struct {
	originalWd string
	repoDir    string // git root (real files on disk)
	backupDir  string // backup destination
	cmdErr     error
	cmdOutput  string
}

func (s *envBackupIntSteps) before(_ context.Context, _ *godog.Scenario) (context.Context, error) {
	s.originalWd, _ = os.Getwd()
	s.repoDir = ""
	s.backupDir = ""
	s.cmdErr = nil
	s.cmdOutput = ""
	verbose = false
	quiet = false
	output = "text"
	envBackupDir = ""
	envBackupWorktreeAware = false
	envBackupFn = envbackup.Backup
	// Restore real OS functions.
	osGetwd = os.Getwd
	osStat = os.Stat
	return context.Background(), nil
}

func (s *envBackupIntSteps) after(_ context.Context, _ *godog.Scenario, _ error) (context.Context, error) {
	_ = os.Chdir(s.originalWd)
	envBackupDir = ""
	envBackupWorktreeAware = false
	envBackupFn = envbackup.Backup
	confirmFn = envbackup.DefaultConfirmFn
	osGetwd = os.Getwd
	osStat = os.Stat
	envBackupForce = false
	envBackupIncludeConfig = false
	if s.repoDir != "" {
		_ = os.RemoveAll(s.repoDir)
	}
	if s.backupDir != "" {
		_ = os.RemoveAll(s.backupDir)
	}
	return context.Background(), nil
}

// makeRepo creates a temp dir with a .git directory (simulating a repo root).
func (s *envBackupIntSteps) makeRepo(pattern string) (string, error) {
	dir, err := os.MkdirTemp("", pattern)
	if err != nil {
		return "", fmt.Errorf("create repo dir: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(dir, ".git"), 0o755); err != nil {
		return "", fmt.Errorf("create .git dir: %w", err)
	}
	return dir, nil
}

// makeBackupDir creates a temp dir outside the repo.
func (s *envBackupIntSteps) makeBackupDir(pattern string) (string, error) {
	dir, err := os.MkdirTemp("", pattern)
	if err != nil {
		return "", fmt.Errorf("create backup dir: %w", err)
	}
	return dir, nil
}

// writeFile creates a file at relPath under dir with the given content.
func writeEnvFile(dir, relPath, content string) error {
	full := filepath.Join(dir, relPath)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		return fmt.Errorf("mkdir for %s: %w", relPath, err)
	}
	return os.WriteFile(full, []byte(content), 0o644)
}

// --- Given steps ---

func (s *envBackupIntSteps) aGitRepositoryContainingEnvFilesAtRootAndSubdirs() error {
	repo, err := s.makeRepo("int-env-backup-multi-*")
	if err != nil {
		return err
	}
	s.repoDir = repo
	if err := writeEnvFile(repo, ".env", "ROOT=1\n"); err != nil {
		return err
	}
	if err := writeEnvFile(repo, "apps/web/.env", "WEB=1\n"); err != nil {
		return err
	}
	backup, err := s.makeBackupDir("int-env-backup-dest-*")
	if err != nil {
		return err
	}
	s.backupDir = backup
	envBackupDir = backup
	return os.Chdir(repo)
}

func (s *envBackupIntSteps) aGitRepositoryContainingAnEnvFileAtRoot() error {
	repo, err := s.makeRepo("int-env-backup-single-*")
	if err != nil {
		return err
	}
	s.repoDir = repo
	if err := writeEnvFile(repo, ".env", "KEY=val\n"); err != nil {
		return err
	}
	backup, err := s.makeBackupDir("int-env-backup-dest-*")
	if err != nil {
		return err
	}
	s.backupDir = backup
	envBackupDir = backup
	return os.Chdir(repo)
}

func (s *envBackupIntSteps) aGitRepositoryContainingSymlinkOversizedAndRegularEnvFile() error {
	repo, err := s.makeRepo("int-env-backup-mixed-*")
	if err != nil {
		return err
	}
	s.repoDir = repo

	// Regular file.
	if err := writeEnvFile(repo, ".env", "REGULAR=1\n"); err != nil {
		return err
	}

	// Symlink .env.symlink → .env.
	target := filepath.Join(repo, ".env")
	link := filepath.Join(repo, ".env.symlink")
	if err := os.Symlink(target, link); err != nil {
		return fmt.Errorf("create symlink: %w", err)
	}

	// Oversized file (>1 MB).
	bigContent := strings.Repeat("x", 1024*1024+1)
	if err := writeEnvFile(repo, ".env.big", bigContent); err != nil {
		return err
	}

	backup, err := s.makeBackupDir("int-env-backup-dest-*")
	if err != nil {
		return err
	}
	s.backupDir = backup
	envBackupDir = backup
	return os.Chdir(repo)
}

func (s *envBackupIntSteps) aGitRepositoryContainingNoEnvFiles() error {
	repo, err := s.makeRepo("int-env-backup-empty-*")
	if err != nil {
		return err
	}
	s.repoDir = repo
	backup, err := s.makeBackupDir("int-env-backup-dest-*")
	if err != nil {
		return err
	}
	s.backupDir = backup
	envBackupDir = backup
	return os.Chdir(repo)
}

func (s *envBackupIntSteps) aGitRepositoryContainingEnvFilesInAutoGeneratedDirs() error {
	repo, err := s.makeRepo("int-env-backup-autodirs-*")
	if err != nil {
		return err
	}
	s.repoDir = repo

	skipDirs := []string{
		"node_modules", "dist", "build", ".next",
		"__pycache__", "target", "vendor", "coverage", "generated-contracts",
	}
	for _, dir := range skipDirs {
		if err := writeEnvFile(repo, filepath.Join(dir, ".env"), "SKIP=1\n"); err != nil {
			return err
		}
	}

	backup, err := s.makeBackupDir("int-env-backup-dest-*")
	if err != nil {
		return err
	}
	s.backupDir = backup
	envBackupDir = backup
	return os.Chdir(repo)
}

func (s *envBackupIntSteps) aGitRepositoryWhereAppsWebNodeModulesHasEnvAndAppsWebHasLocal() error {
	repo, err := s.makeRepo("int-env-backup-nested-*")
	if err != nil {
		return err
	}
	s.repoDir = repo

	if err := writeEnvFile(repo, "apps/web/node_modules/.env", "SKIP=1\n"); err != nil {
		return err
	}
	if err := writeEnvFile(repo, "apps/web/.env.local", "LOCAL=1\n"); err != nil {
		return err
	}

	backup, err := s.makeBackupDir("int-env-backup-dest-*")
	if err != nil {
		return err
	}
	s.backupDir = backup
	envBackupDir = backup
	return os.Chdir(repo)
}

func (s *envBackupIntSteps) aGitWorktreeContainingEnvFileAtRoot() error {
	// Simulate a linked worktree: .git is a FILE.
	tmpDir, err := os.MkdirTemp("", "int-env-backup-worktree-*")
	if err != nil {
		return fmt.Errorf("create worktree dir: %w", err)
	}
	s.repoDir = tmpDir

	if err := os.WriteFile(filepath.Join(tmpDir, ".git"), []byte("gitdir: /some/real/.git/worktrees/feature\n"), 0o644); err != nil {
		return fmt.Errorf("write .git file: %w", err)
	}
	if err := writeEnvFile(tmpDir, ".env", "WORKTREE=1\n"); err != nil {
		return err
	}

	backup, err := s.makeBackupDir("int-env-backup-dest-*")
	if err != nil {
		return err
	}
	s.backupDir = backup
	envBackupDir = backup
	return os.Chdir(tmpDir)
}

func (s *envBackupIntSteps) aGitWorktreeNamedFeatureBranchWithEnvFile() error {
	// Create a directory whose basename is "feature-branch".
	parent, err := os.MkdirTemp("", "int-env-backup-wt-parent-*")
	if err != nil {
		return fmt.Errorf("create parent dir: %w", err)
	}
	featureBranchDir := filepath.Join(parent, "feature-branch")
	if err := os.MkdirAll(featureBranchDir, 0o755); err != nil {
		return fmt.Errorf("create feature-branch dir: %w", err)
	}
	s.repoDir = parent // parent holds the named dir; cleanup removes both

	if err := os.WriteFile(filepath.Join(featureBranchDir, ".git"), []byte("gitdir: /some/real/.git/worktrees/feature-branch\n"), 0o644); err != nil {
		return fmt.Errorf("write .git file: %w", err)
	}
	if err := writeEnvFile(featureBranchDir, ".env", "WT=1\n"); err != nil {
		return err
	}

	backup, err := s.makeBackupDir("int-env-backup-dest-*")
	if err != nil {
		return err
	}
	s.backupDir = backup
	envBackupDir = backup
	return os.Chdir(featureBranchDir)
}

func (s *envBackupIntSteps) theMainGitRepositoryNamedOpenShariaEnterpriseWithEnvFile() error {
	parent, err := os.MkdirTemp("", "int-env-backup-main-parent-*")
	if err != nil {
		return fmt.Errorf("create parent dir: %w", err)
	}
	mainRepoDir := filepath.Join(parent, "open-sharia-enterprise")
	if err := os.MkdirAll(mainRepoDir, 0o755); err != nil {
		return fmt.Errorf("create main repo dir: %w", err)
	}
	s.repoDir = parent

	if err := os.MkdirAll(filepath.Join(mainRepoDir, ".git"), 0o755); err != nil {
		return fmt.Errorf("create .git dir: %w", err)
	}
	if err := writeEnvFile(mainRepoDir, ".env", "MAIN=1\n"); err != nil {
		return err
	}

	backup, err := s.makeBackupDir("int-env-backup-dest-*")
	if err != nil {
		return err
	}
	s.backupDir = backup
	envBackupDir = backup
	return os.Chdir(mainRepoDir)
}

// --- When steps ---

func (s *envBackupIntSteps) runCmd() error {
	buf := new(bytes.Buffer)
	envBackupCmd.SetOut(buf)
	envBackupCmd.SetErr(buf)
	s.cmdErr = envBackupCmd.RunE(envBackupCmd, []string{})
	s.cmdOutput = buf.String()
	return nil
}

func (s *envBackupIntSteps) theDeveloperRunsEnvBackup() error {
	return s.runCmd()
}

func (s *envBackupIntSteps) theDeveloperRunsEnvBackupWithDirOutside() error {
	// backupDir already set to a dir outside the repo.
	return s.runCmd()
}

func (s *envBackupIntSteps) theDeveloperRunsEnvBackupWithDirInside() error {
	// Use os.Getwd() for the canonical path (resolves symlinks on macOS).
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getwd: %w", err)
	}
	// Set the backup dir to a subdirectory inside the repo root.
	insideDir := filepath.Join(cwd, "env-backup-inside")
	if err := os.MkdirAll(insideDir, 0o755); err != nil {
		return fmt.Errorf("create inside dir: %w", err)
	}
	envBackupDir = insideDir
	return s.runCmd()
}

func (s *envBackupIntSteps) theDeveloperRunsEnvBackupWithOutputJSON() error {
	output = "json"
	return s.runCmd()
}

func (s *envBackupIntSteps) theDeveloperRunsEnvBackupWithWorktreeAware() error {
	envBackupWorktreeAware = true
	return s.runCmd()
}

// --- Then steps ---

func (s *envBackupIntSteps) theCommandExitsSuccessfully() error {
	if s.cmdErr != nil {
		return fmt.Errorf("expected success but got: %v\nOutput: %s", s.cmdErr, s.cmdOutput)
	}
	return nil
}

func (s *envBackupIntSteps) theCommandExitsWithAFailureCode() error {
	if s.cmdErr == nil {
		return fmt.Errorf("expected failure but succeeded\nOutput: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupIntSteps) eachEnvFileCopiedPreservingRelativePath() error {
	// Verify .env appears in the backup dir at the correct relative path.
	envPath := filepath.Join(s.backupDir, ".env")
	if _, err := os.Stat(envPath); err != nil {
		return fmt.Errorf("expected %s to exist after backup, got: %v", envPath, err)
	}
	return nil
}

func (s *envBackupIntSteps) theOutputListsEachBackedUpFile() error {
	if !strings.Contains(s.cmdOutput, ".env") {
		return fmt.Errorf("expected .env in output, got: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupIntSteps) theEnvFileCopiedToSpecifiedDirPreservingPath() error {
	return s.eachEnvFileCopiedPreservingRelativePath()
}

func (s *envBackupIntSteps) theOutputWarnsBackupDirMustBeOutside() error {
	if s.cmdErr == nil {
		return fmt.Errorf("expected an error but command succeeded")
	}
	if !strings.Contains(s.cmdErr.Error(), "inside repo") {
		return fmt.Errorf("expected 'inside repo' error, got: %v", s.cmdErr)
	}
	return nil
}

func (s *envBackupIntSteps) theSymlinkedEnvFileSkippedWithWarning() error {
	lower := strings.ToLower(s.cmdOutput)
	if !strings.Contains(lower, "backup complete") {
		return fmt.Errorf("expected 'backup complete' in output, got: %s", s.cmdOutput)
	}
	// The symlink should be skipped (not copied).
	symlinkPath := filepath.Join(s.backupDir, ".env.symlink")
	if _, err := os.Stat(symlinkPath); err == nil {
		return fmt.Errorf("expected .env.symlink to be skipped but it was copied")
	}
	return nil
}

func (s *envBackupIntSteps) theOversizedEnvFileSkippedWithWarning() error {
	bigPath := filepath.Join(s.backupDir, ".env.big")
	if _, err := os.Stat(bigPath); err == nil {
		return fmt.Errorf("expected .env.big to be skipped but it was copied")
	}
	return nil
}

func (s *envBackupIntSteps) theRegularEnvFileCopiedToBackupDir() error {
	envPath := filepath.Join(s.backupDir, ".env")
	if _, err := os.Stat(envPath); err != nil {
		return fmt.Errorf("expected .env to be copied, got: %v", err)
	}
	return nil
}

func (s *envBackupIntSteps) theOutputReportsZeroFilesBackedUp() error {
	if !strings.Contains(s.cmdOutput, "0 file(s)") {
		return fmt.Errorf("expected '0 file(s)' in output, got: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupIntSteps) theOutputIsValidJSON() error {
	var parsed map[string]any
	if err := json.Unmarshal([]byte(s.cmdOutput), &parsed); err != nil {
		return fmt.Errorf("output is not valid JSON: %v\nOutput: %s", err, s.cmdOutput)
	}
	return nil
}

func (s *envBackupIntSteps) theJSONIncludesDirectionDirFilesCountsBackup() error {
	var parsed map[string]any
	if err := json.Unmarshal([]byte(s.cmdOutput), &parsed); err != nil {
		return fmt.Errorf("output is not valid JSON: %v\nOutput: %s", err, s.cmdOutput)
	}
	for _, key := range []string{"direction", "dir", "files", "copied", "skipped"} {
		if _, ok := parsed[key]; !ok {
			return fmt.Errorf("expected JSON key %q but not found\nOutput: %s", key, s.cmdOutput)
		}
	}
	return nil
}

func (s *envBackupIntSteps) noneOfEnvFilesInAutoGeneratedDirsBacked() error {
	if !strings.Contains(s.cmdOutput, "0 file(s)") {
		return fmt.Errorf("expected 0 files backed up (all in skip dirs), got: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupIntSteps) onlyAppsWebEnvLocalCopied() error {
	localPath := filepath.Join(s.backupDir, "apps", "web", ".env.local")
	if _, err := os.Stat(localPath); err != nil {
		return fmt.Errorf("expected apps/web/.env.local in backup, got: %v", err)
	}
	return nil
}

func (s *envBackupIntSteps) theEnvFileInsideNodeModulesNotBacked() error {
	nmPath := filepath.Join(s.backupDir, "apps", "web", "node_modules", ".env")
	if _, err := os.Stat(nmPath); err == nil {
		return fmt.Errorf("expected node_modules/.env to be absent from backup, but it was copied")
	}
	return nil
}

func (s *envBackupIntSteps) theEnvFileCopiedWithFlatStructure() error {
	return s.eachEnvFileCopiedPreservingRelativePath()
}

func (s *envBackupIntSteps) theEnvFileCopiedUnderFeatureBranchSubdir() error {
	// With --worktree-aware the file goes under backupDir/feature-branch/.env
	wt := filepath.Join(s.backupDir, "feature-branch", ".env")
	if _, err := os.Stat(wt); err != nil {
		return fmt.Errorf("expected file at %s after worktree-aware backup, got: %v", wt, err)
	}
	return nil
}

func (s *envBackupIntSteps) theEnvFileCopiedUnderOpenShariaEnterpriseSubdir() error {
	ose := filepath.Join(s.backupDir, "open-sharia-enterprise", ".env")
	if _, err := os.Stat(ose); err != nil {
		return fmt.Errorf("expected file at %s after worktree-aware backup, got: %v", ose, err)
	}
	return nil
}

// --- Confirm Given steps ---

func (s *envBackupIntSteps) theBackupDirAlreadyContainsBackedUpEnvFile() error {
	// Pre-populate the backup dir with .env so conflicts are detected.
	if s.backupDir == "" {
		return fmt.Errorf("backupDir not set; Given step for repo must run first")
	}
	return writeEnvFile(s.backupDir, ".env", "OLD=1\n")
}

func (s *envBackupIntSteps) theBackupDirIsEmpty() error {
	// backupDir is already created fresh and empty by the repo Given step.
	return nil
}

// --- Confirm When steps ---

func (s *envBackupIntSteps) theDeveloperRunsEnvBackupAndConfirmsOverwrite() error {
	envBackupForce = true // In integration tests, use force to simulate confirmation
	return s.runCmd()
}

func (s *envBackupIntSteps) theDeveloperRunsEnvBackupAndDeclinesOverwrite() error {
	// Inject a confirmFn that declines.
	confirmFn = func(_ io.Reader, _ io.Writer) func([]string) bool {
		return func(_ []string) bool { return false }
	}
	return s.runCmd()
}

func (s *envBackupIntSteps) theDeveloperRunsEnvBackupWithForce() error {
	envBackupForce = true
	return s.runCmd()
}

// --- Confirm Then steps ---

func (s *envBackupIntSteps) theEnvFileOverwrittenInBackupDir() error {
	envPath := filepath.Join(s.backupDir, ".env")
	content, err := os.ReadFile(envPath)
	if err != nil {
		return fmt.Errorf("expected .env in backup dir: %v", err)
	}
	// Should contain the NEW content from the repo, not "OLD=1".
	if strings.Contains(string(content), "OLD=1") {
		return fmt.Errorf("expected .env to be overwritten but still has old content")
	}
	return nil
}

func (s *envBackupIntSteps) theOutputReportsBackupCancelled() error {
	if !strings.Contains(s.cmdOutput, "cancelled") {
		return fmt.Errorf("expected 'cancelled' in output, got: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupIntSteps) theExistingBackupFileUnchanged() error {
	envPath := filepath.Join(s.backupDir, ".env")
	content, err := os.ReadFile(envPath)
	if err != nil {
		return fmt.Errorf("expected .env to still exist: %v", err)
	}
	if !strings.Contains(string(content), "OLD=1") {
		return fmt.Errorf("expected .env to be unchanged with old content")
	}
	return nil
}

func (s *envBackupIntSteps) theEnvFileOverwrittenWithoutPrompting() error {
	return s.theEnvFileOverwrittenInBackupDir()
}

func (s *envBackupIntSteps) noConfirmationPromptShown() error {
	return nil
}

func (s *envBackupIntSteps) theEnvFileCopiedToBackupDirInt() error {
	envPath := filepath.Join(s.backupDir, ".env")
	if _, err := os.Stat(envPath); err != nil {
		return fmt.Errorf("expected .env in backup dir: %v", err)
	}
	return nil
}

// --- Config Given steps ---

func (s *envBackupIntSteps) aGitRepoWithEnvFileAndClaudeConfig() error {
	repo, err := s.makeRepo("int-env-backup-config-*")
	if err != nil {
		return err
	}
	s.repoDir = repo
	if err := writeEnvFile(repo, ".env", "KEY=val\n"); err != nil {
		return err
	}
	if err := writeEnvFile(repo, ".claude/settings.local.json", `{"key":"val"}`); err != nil {
		return err
	}
	backup, err := s.makeBackupDir("int-env-backup-config-dest-*")
	if err != nil {
		return err
	}
	s.backupDir = backup
	envBackupDir = backup
	return os.Chdir(repo)
}

func (s *envBackupIntSteps) aGitRepoWithEnvFileButNoKnownConfigFiles() error {
	repo, err := s.makeRepo("int-env-backup-noconfig-*")
	if err != nil {
		return err
	}
	s.repoDir = repo
	if err := writeEnvFile(repo, ".env", "KEY=val\n"); err != nil {
		return err
	}
	backup, err := s.makeBackupDir("int-env-backup-noconfig-dest-*")
	if err != nil {
		return err
	}
	s.backupDir = backup
	envBackupDir = backup
	return os.Chdir(repo)
}

// --- Config When steps ---

func (s *envBackupIntSteps) theDeveloperRunsEnvBackupWithIncludeConfigForce() error {
	envBackupIncludeConfig = true
	envBackupForce = true
	return s.runCmd()
}

func (s *envBackupIntSteps) theDeveloperRunsEnvBackupWithForceOnly() error {
	envBackupForce = true
	return s.runCmd()
}

// --- Config Then steps ---

func (s *envBackupIntSteps) theClaudeConfigCopiedToBackupDir() error {
	configPath := filepath.Join(s.backupDir, ".claude", "settings.local.json")
	if _, err := os.Stat(configPath); err != nil {
		return fmt.Errorf("expected .claude/settings.local.json in backup dir: %v", err)
	}
	return nil
}

func (s *envBackupIntSteps) theClaudeConfigNotCopiedToBackupDir() error {
	configPath := filepath.Join(s.backupDir, ".claude", "settings.local.json")
	if _, err := os.Stat(configPath); err == nil {
		return fmt.Errorf("expected .claude/settings.local.json to NOT be in backup dir")
	}
	return nil
}

func (s *envBackupIntSteps) onlyTheEnvFileCopiedToBackupDir() error {
	if !strings.Contains(s.cmdOutput, "1 file(s)") {
		return fmt.Errorf("expected '1 file(s)' in output, got: %s", s.cmdOutput)
	}
	return nil
}

func TestIntegrationEnvBackup(t *testing.T) {
	s := &envBackupIntSteps{}
	suite := godog.TestSuite{
		ScenarioInitializer: func(sc *godog.ScenarioContext) {
			sc.Before(s.before)
			sc.After(s.after)

			// Given steps.
			sc.Step(stepRepoWithEnvFilesAtRootAndSubdirs, s.aGitRepositoryContainingEnvFilesAtRootAndSubdirs)
			sc.Step(stepRepoWithEnvFileAtRoot, s.aGitRepositoryContainingAnEnvFileAtRoot)
			sc.Step(stepRepoWithSymlinkOversizedAndRegularEnvFile, s.aGitRepositoryContainingSymlinkOversizedAndRegularEnvFile)
			sc.Step(stepRepoWithNoEnvFiles, s.aGitRepositoryContainingNoEnvFiles)
			sc.Step(stepRepoWithEnvFilesInAutoGeneratedDirs, s.aGitRepositoryContainingEnvFilesInAutoGeneratedDirs)
			sc.Step(stepRepoWithNestedNodeModulesEnvAndLocalEnv, s.aGitRepositoryWhereAppsWebNodeModulesHasEnvAndAppsWebHasLocal)
			sc.Step(stepWorktreeWithEnvFileAtRoot, s.aGitWorktreeContainingEnvFileAtRoot)
			sc.Step(stepWorktreeNamedFeatureBranchWithEnvFile, s.aGitWorktreeNamedFeatureBranchWithEnvFile)
			sc.Step(stepMainRepoNamedOpenShariaEnterpriseWithEnv, s.theMainGitRepositoryNamedOpenShariaEnterpriseWithEnvFile)

			// When steps.
			sc.Step(stepDeveloperRunsEnvBackup, s.theDeveloperRunsEnvBackup)
			sc.Step(stepDeveloperRunsEnvBackupWithDirOutside, s.theDeveloperRunsEnvBackupWithDirOutside)
			sc.Step(stepDeveloperRunsEnvBackupWithDirInside, s.theDeveloperRunsEnvBackupWithDirInside)
			sc.Step(stepDeveloperRunsEnvBackupWithOutputJSON, s.theDeveloperRunsEnvBackupWithOutputJSON)
			sc.Step(stepDeveloperRunsEnvBackupWithWorktreeAware, s.theDeveloperRunsEnvBackupWithWorktreeAware)

			// Then steps.
			sc.Step(stepExitsSuccessfully, s.theCommandExitsSuccessfully)
			sc.Step(stepExitsWithFailure, s.theCommandExitsWithAFailureCode)
			sc.Step(stepEachEnvFileCopiedPreservingRelativePath, s.eachEnvFileCopiedPreservingRelativePath)
			sc.Step(stepOutputListsEachBackedUpFile, s.theOutputListsEachBackedUpFile)
			sc.Step(stepEnvFileCopiedToSpecifiedDirPreservingPath, s.theEnvFileCopiedToSpecifiedDirPreservingPath)
			sc.Step(stepOutputWarnsBackupDirMustBeOutside, s.theOutputWarnsBackupDirMustBeOutside)
			sc.Step(stepSymlinkedEnvFileSkippedWithWarning, s.theSymlinkedEnvFileSkippedWithWarning)
			sc.Step(stepOversizedEnvFileSkippedWithWarning, s.theOversizedEnvFileSkippedWithWarning)
			sc.Step(stepRegularEnvFileCopiedToBackupDir, s.theRegularEnvFileCopiedToBackupDir)
			sc.Step(stepOutputReportsZeroFilesBackedUp, s.theOutputReportsZeroFilesBackedUp)
			sc.Step(stepOutputIsValidJSON, s.theOutputIsValidJSON)
			sc.Step(stepJSONIncludesDirectionDirFilesCountsBackup, s.theJSONIncludesDirectionDirFilesCountsBackup)
			sc.Step(stepNoneOfEnvFilesInAutoGeneratedDirsBacked, s.noneOfEnvFilesInAutoGeneratedDirsBacked)
			sc.Step(stepOnlyAppsWebEnvLocalCopied, s.onlyAppsWebEnvLocalCopied)
			sc.Step(stepEnvFileInsideNodeModulesNotBacked, s.theEnvFileInsideNodeModulesNotBacked)
			sc.Step(stepEnvFileCopiedWithFlatStructure, s.theEnvFileCopiedWithFlatStructure)
			sc.Step(stepEnvFileCopiedUnderFeatureBranchSubdir, s.theEnvFileCopiedUnderFeatureBranchSubdir)
			sc.Step(stepEnvFileCopiedUnderOpenShariaEnterpriseSubdir, s.theEnvFileCopiedUnderOpenShariaEnterpriseSubdir)

			// Confirm scenario steps.
			sc.Step(stepBackupDirAlreadyContainsBackedUpEnvFile, s.theBackupDirAlreadyContainsBackedUpEnvFile)
			sc.Step(stepBackupDirIsEmpty, s.theBackupDirIsEmpty)
			sc.Step(stepDeveloperRunsEnvBackupAndConfirmsOverwrite, s.theDeveloperRunsEnvBackupAndConfirmsOverwrite)
			sc.Step(stepDeveloperRunsEnvBackupAndDeclinesOverwrite, s.theDeveloperRunsEnvBackupAndDeclinesOverwrite)
			sc.Step(stepDeveloperRunsEnvBackupWithForce, s.theDeveloperRunsEnvBackupWithForce)
			sc.Step(stepEnvFileOverwrittenInBackupDir, s.theEnvFileOverwrittenInBackupDir)
			sc.Step(stepOutputReportsBackupCancelled, s.theOutputReportsBackupCancelled)
			sc.Step(stepExistingBackupFileUnchanged, s.theExistingBackupFileUnchanged)
			sc.Step(stepEnvFileOverwrittenWithoutPrompting, s.theEnvFileOverwrittenWithoutPrompting)
			sc.Step(stepNoConfirmationPromptShown, s.noConfirmationPromptShown)
			sc.Step(stepEnvFileCopiedToBackupDir, s.theEnvFileCopiedToBackupDirInt)

			// Config scenario steps.
			sc.Step(stepRepoWithEnvFileAndClaudeConfig, s.aGitRepoWithEnvFileAndClaudeConfig)
			sc.Step(stepRepoWithEnvFileButNoKnownConfigFiles, s.aGitRepoWithEnvFileButNoKnownConfigFiles)
			sc.Step(stepDeveloperRunsEnvBackupWithIncludeConfigForce, s.theDeveloperRunsEnvBackupWithIncludeConfigForce)
			sc.Step(stepDeveloperRunsEnvBackupWithForceOnly, s.theDeveloperRunsEnvBackupWithForceOnly)
			sc.Step(stepClaudeConfigCopiedToBackupDir, s.theClaudeConfigCopiedToBackupDir)
			sc.Step(stepClaudeConfigNotCopiedToBackupDir, s.theClaudeConfigNotCopiedToBackupDir)
			sc.Step(stepOnlyEnvFileCopiedToBackupDir, s.onlyTheEnvFileCopiedToBackupDir)
		},
		Options: &godog.Options{
			Format:   "pretty",
			Paths:    []string{specsIntEnvBackupDir},
			Tags:     "@env-backup,@env-backup-confirm,@env-backup-config",
			TestingT: t,
		},
	}
	if suite.Run() != 0 {
		t.Fatal("non-zero status returned, failed to run integration feature tests")
	}
}
