package cmd

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/cucumber/godog"
	"github.com/wahidyankf/open-sharia-enterprise/apps/rhino-cli/internal/envbackup"
)

var specsDirUnitEnvBackup = func() string {
	_, f, _, _ := runtime.Caller(0)
	return filepath.Join(filepath.Dir(f), "../../../specs/apps/rhino-cli/cli/gherkin")
}()

type envBackupUnitSteps struct {
	cmdErr    error
	cmdOutput string
	backupDir string // temp dir used as backup destination
	repoDir   string // temp dir used as fake repo root
}

func (s *envBackupUnitSteps) before(_ context.Context, _ *godog.Scenario) (context.Context, error) {
	verbose = false
	quiet = false
	output = "text"
	envBackupDir = ""
	envBackupWorktreeAware = false
	envBackupForce = false
	envBackupIncludeConfig = false
	s.cmdErr = nil
	s.cmdOutput = ""
	s.backupDir = ""
	s.repoDir = ""

	// Mock findGitRoot via osGetwd/osStat — default to /mock-repo.
	osGetwd = func() (string, error) { return "/mock-repo", nil }
	osStat = func(name string) (os.FileInfo, error) {
		if name == "/mock-repo/.git" {
			return &mockFileInfo{name: ".git", isDir: true}, nil
		}
		return nil, os.ErrNotExist
	}

	// Default mock: backup succeeds with 2 copied files.
	envBackupFn = func(opts envbackup.Options) (*envbackup.Result, error) {
		return &envbackup.Result{
			Direction: "backup",
			Dir:       opts.BackupDir,
			Files: []envbackup.FileEntry{
				{RelPath: ".env", AbsPath: "/mock-repo/.env", Size: 100},
				{RelPath: "apps/web/.env", AbsPath: "/mock-repo/apps/web/.env", Size: 200},
			},
			Copied:  2,
			Skipped: 0,
		}, nil
	}

	return context.Background(), nil
}

func (s *envBackupUnitSteps) after(_ context.Context, _ *godog.Scenario, _ error) (context.Context, error) {
	envBackupFn = envbackup.Backup
	confirmFn = envbackup.DefaultConfirmFn
	osGetwd = os.Getwd
	osStat = os.Stat
	envBackupForce = false
	envBackupIncludeConfig = false
	if s.backupDir != "" {
		_ = os.RemoveAll(s.backupDir)
	}
	if s.repoDir != "" {
		_ = os.RemoveAll(s.repoDir)
	}
	return context.Background(), nil
}

// --- Given steps ---

func (s *envBackupUnitSteps) aGitRepositoryContainingEnvFilesAtRootAndSubdirs() error {
	envBackupFn = func(opts envbackup.Options) (*envbackup.Result, error) {
		return &envbackup.Result{
			Direction: "backup",
			Dir:       opts.BackupDir,
			Files: []envbackup.FileEntry{
				{RelPath: ".env", AbsPath: "/mock-repo/.env", Size: 100},
				{RelPath: "apps/web/.env", AbsPath: "/mock-repo/apps/web/.env", Size: 200},
			},
			Copied:  2,
			Skipped: 0,
		}, nil
	}
	return nil
}

func (s *envBackupUnitSteps) aGitRepositoryContainingAnEnvFileAtRoot() error {
	envBackupFn = func(opts envbackup.Options) (*envbackup.Result, error) {
		return &envbackup.Result{
			Direction: "backup",
			Dir:       opts.BackupDir,
			Files: []envbackup.FileEntry{
				{RelPath: ".env", AbsPath: "/mock-repo/.env", Size: 100},
			},
			Copied:  1,
			Skipped: 0,
		}, nil
	}
	return nil
}

func (s *envBackupUnitSteps) aGitRepositoryContainingSymlinkOversizedAndRegularEnvFile() error {
	envBackupFn = func(opts envbackup.Options) (*envbackup.Result, error) {
		return &envbackup.Result{
			Direction: "backup",
			Dir:       opts.BackupDir,
			Files: []envbackup.FileEntry{
				{RelPath: ".env.symlink", AbsPath: "/mock-repo/.env.symlink", Skipped: true, Reason: "symlink"},
				{RelPath: ".env.big", AbsPath: "/mock-repo/.env.big", Size: 2 * 1024 * 1024, Skipped: true, Reason: "file too large (2097152 bytes > 1048576)"},
				{RelPath: ".env", AbsPath: "/mock-repo/.env", Size: 100},
			},
			Copied:  1,
			Skipped: 2,
		}, nil
	}
	return nil
}

func (s *envBackupUnitSteps) aGitRepositoryContainingNoEnvFiles() error {
	envBackupFn = func(opts envbackup.Options) (*envbackup.Result, error) {
		return &envbackup.Result{
			Direction: "backup",
			Dir:       opts.BackupDir,
			Files:     []envbackup.FileEntry{},
			Copied:    0,
			Skipped:   0,
		}, nil
	}
	return nil
}

func (s *envBackupUnitSteps) aGitRepositoryContainingEnvFilesInAutoGeneratedDirs() error {
	envBackupFn = func(opts envbackup.Options) (*envbackup.Result, error) {
		return &envbackup.Result{
			Direction: "backup",
			Dir:       opts.BackupDir,
			Files:     []envbackup.FileEntry{},
			Copied:    0,
			Skipped:   0,
		}, nil
	}
	return nil
}

func (s *envBackupUnitSteps) aGitRepositoryWhereAppsWebNodeModulesHasEnvAndAppsWebHasLocal() error {
	envBackupFn = func(opts envbackup.Options) (*envbackup.Result, error) {
		return &envbackup.Result{
			Direction: "backup",
			Dir:       opts.BackupDir,
			Files: []envbackup.FileEntry{
				{RelPath: "apps/web/.env.local", AbsPath: "/mock-repo/apps/web/.env.local", Size: 50},
			},
			Copied:  1,
			Skipped: 0,
		}, nil
	}
	return nil
}

func (s *envBackupUnitSteps) aGitWorktreeContainingEnvFileAtRoot() error {
	envBackupFn = func(opts envbackup.Options) (*envbackup.Result, error) {
		return &envbackup.Result{
			Direction: "backup",
			Dir:       opts.BackupDir,
			Files: []envbackup.FileEntry{
				{RelPath: ".env", AbsPath: "/mock-repo/.env", Size: 100},
			},
			Copied:  1,
			Skipped: 0,
		}, nil
	}
	return nil
}

func (s *envBackupUnitSteps) aGitWorktreeNamedFeatureBranchWithEnvFile() error {
	// Create a temp dir simulating a worktree (dir-name is "feature-branch").
	tmpRepo, err := os.MkdirTemp("", "feature-branch-*")
	if err != nil {
		return fmt.Errorf("create temp worktree dir: %w", err)
	}
	// Rename so basename is "feature-branch".
	featureBranchDir := filepath.Join(filepath.Dir(tmpRepo), "feature-branch")
	if err := os.Rename(tmpRepo, featureBranchDir); err != nil {
		// If rename fails (cross-device), just keep tmpRepo.
		featureBranchDir = tmpRepo
	}
	s.repoDir = featureBranchDir

	// Create .git as a file to simulate a linked worktree.
	if err := os.WriteFile(filepath.Join(featureBranchDir, ".git"), []byte("gitdir: /some/real/.git\n"), 0o644); err != nil {
		return fmt.Errorf("write .git file: %w", err)
	}

	osGetwd = func() (string, error) { return featureBranchDir, nil }
	osStat = func(name string) (os.FileInfo, error) {
		if name == filepath.Join(featureBranchDir, ".git") {
			return &mockFileInfo{name: ".git", isDir: false}, nil
		}
		return nil, os.ErrNotExist
	}

	envBackupFn = func(opts envbackup.Options) (*envbackup.Result, error) {
		return &envbackup.Result{
			Direction:    "backup",
			Dir:          opts.BackupDir,
			WorktreeName: "feature-branch",
			Files: []envbackup.FileEntry{
				{RelPath: ".env", AbsPath: filepath.Join(featureBranchDir, ".env"), Size: 100},
			},
			Copied:  1,
			Skipped: 0,
		}, nil
	}
	return nil
}

func (s *envBackupUnitSteps) theMainGitRepositoryNamedOpenShariaEnterpriseWithEnvFile() error {
	// Create a temp dir simulating main repo (dir-name is "open-sharia-enterprise").
	tmpRepo, err := os.MkdirTemp("", "open-sharia-enterprise-*")
	if err != nil {
		return fmt.Errorf("create temp repo dir: %w", err)
	}
	mainRepoDir := filepath.Join(filepath.Dir(tmpRepo), "open-sharia-enterprise")
	if err := os.Rename(tmpRepo, mainRepoDir); err != nil {
		mainRepoDir = tmpRepo
	}
	s.repoDir = mainRepoDir

	// Create .git as a directory to simulate a normal repo.
	if err := os.MkdirAll(filepath.Join(mainRepoDir, ".git"), 0o755); err != nil {
		return fmt.Errorf("create .git dir: %w", err)
	}

	osGetwd = func() (string, error) { return mainRepoDir, nil }
	osStat = func(name string) (os.FileInfo, error) {
		if name == filepath.Join(mainRepoDir, ".git") {
			return &mockFileInfo{name: ".git", isDir: true}, nil
		}
		return nil, os.ErrNotExist
	}

	envBackupFn = func(opts envbackup.Options) (*envbackup.Result, error) {
		return &envbackup.Result{
			Direction:    "backup",
			Dir:          opts.BackupDir,
			WorktreeName: "open-sharia-enterprise",
			Files: []envbackup.FileEntry{
				{RelPath: ".env", AbsPath: filepath.Join(mainRepoDir, ".env"), Size: 100},
			},
			Copied:  1,
			Skipped: 0,
		}, nil
	}
	return nil
}

// --- When steps ---

func (s *envBackupUnitSteps) runEnvBackupCmd() error {
	// Use a temp dir as backup destination so ExpandTilde and Abs don't fail.
	tmpBackup, err := os.MkdirTemp("", "env-backup-dest-*")
	if err != nil {
		return fmt.Errorf("create temp backup dir: %w", err)
	}
	s.backupDir = tmpBackup
	envBackupDir = tmpBackup

	buf := new(bytes.Buffer)
	envBackupCmd.SetOut(buf)
	envBackupCmd.SetErr(buf)
	s.cmdErr = envBackupCmd.RunE(envBackupCmd, []string{})
	s.cmdOutput = buf.String()
	return nil
}

func (s *envBackupUnitSteps) theDeveloperRunsEnvBackup() error {
	return s.runEnvBackupCmd()
}

func (s *envBackupUnitSteps) theDeveloperRunsEnvBackupWithDirOutside() error {
	return s.runEnvBackupCmd()
}

func (s *envBackupUnitSteps) theDeveloperRunsEnvBackupWithDirInside() error {
	// Simulate the envBackupFn returning an "inside repo root" error.
	envBackupFn = func(opts envbackup.Options) (*envbackup.Result, error) {
		return nil, fmt.Errorf("backup dir %s is inside repo root %s; choose a directory outside the repo", opts.BackupDir, opts.RepoRoot)
	}

	// Use a path that the cmd layer will resolve to something inside the repo.
	// The mock envBackupFn will return the error regardless.
	tmpBackup, err := os.MkdirTemp("", "env-backup-inside-*")
	if err != nil {
		return fmt.Errorf("create temp dir: %w", err)
	}
	s.backupDir = tmpBackup
	envBackupDir = tmpBackup

	buf := new(bytes.Buffer)
	envBackupCmd.SetOut(buf)
	envBackupCmd.SetErr(buf)
	s.cmdErr = envBackupCmd.RunE(envBackupCmd, []string{})
	s.cmdOutput = buf.String()
	return nil
}

func (s *envBackupUnitSteps) theDeveloperRunsEnvBackupWithOutputJSON() error {
	output = "json"
	return s.runEnvBackupCmd()
}

func (s *envBackupUnitSteps) theDeveloperRunsEnvBackupWithWorktreeAware() error {
	envBackupWorktreeAware = true
	return s.runEnvBackupCmd()
}

// --- Then steps ---

func (s *envBackupUnitSteps) theCommandExitsSuccessfully() error {
	if s.cmdErr != nil {
		return fmt.Errorf("expected success but got: %v\nOutput: %s", s.cmdErr, s.cmdOutput)
	}
	return nil
}

func (s *envBackupUnitSteps) theCommandExitsWithAFailureCode() error {
	if s.cmdErr == nil {
		return fmt.Errorf("expected failure but succeeded\nOutput: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupUnitSteps) eachEnvFileCopiedPreservingRelativePath() error {
	lower := strings.ToLower(s.cmdOutput)
	if !strings.Contains(lower, "backup complete") && !strings.Contains(s.cmdOutput, "BACKUP") {
		return fmt.Errorf("expected backup completion in output, got: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupUnitSteps) theOutputListsEachBackedUpFile() error {
	if !strings.Contains(s.cmdOutput, ".env") {
		return fmt.Errorf("expected .env files listed in output, got: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupUnitSteps) theEnvFileCopiedToSpecifiedDirPreservingPath() error {
	return s.eachEnvFileCopiedPreservingRelativePath()
}

func (s *envBackupUnitSteps) theOutputWarnsBackupDirMustBeOutside() error {
	if s.cmdErr == nil {
		return fmt.Errorf("expected an error but command succeeded")
	}
	// The error is returned from RunE; it will contain "inside repo root".
	if !strings.Contains(s.cmdErr.Error(), "inside repo") {
		return fmt.Errorf("expected error about 'inside repo' but got: %v", s.cmdErr)
	}
	return nil
}

func (s *envBackupUnitSteps) theSymlinkedEnvFileSkippedWithWarning() error {
	lower := strings.ToLower(s.cmdOutput)
	if !strings.Contains(lower, "backup complete") {
		return fmt.Errorf("expected 'backup complete' in output, got: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupUnitSteps) theOversizedEnvFileSkippedWithWarning() error {
	return s.theSymlinkedEnvFileSkippedWithWarning()
}

func (s *envBackupUnitSteps) theRegularEnvFileCopiedToBackupDir() error {
	if !strings.Contains(s.cmdOutput, "1 file(s)") {
		return fmt.Errorf("expected '1 file(s)' in output, got: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupUnitSteps) theOutputReportsZeroFilesBackedUp() error {
	if !strings.Contains(s.cmdOutput, "0 file(s)") {
		return fmt.Errorf("expected '0 file(s)' in output, got: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupUnitSteps) theOutputIsValidJSON() error {
	var parsed map[string]any
	if err := json.Unmarshal([]byte(s.cmdOutput), &parsed); err != nil {
		return fmt.Errorf("output is not valid JSON: %v\nOutput: %s", err, s.cmdOutput)
	}
	return nil
}

func (s *envBackupUnitSteps) theJSONIncludesDirectionDirFilesCountsBackup() error {
	var parsed map[string]any
	if err := json.Unmarshal([]byte(s.cmdOutput), &parsed); err != nil {
		return fmt.Errorf("output is not valid JSON: %v\nOutput: %s", err, s.cmdOutput)
	}
	for _, key := range []string{"direction", "dir", "files", "copied", "skipped"} {
		if _, ok := parsed[key]; !ok {
			return fmt.Errorf("expected JSON key %q but not found\nOutput: %s", key, s.cmdOutput)
		}
	}
	return nil
}

func (s *envBackupUnitSteps) noneOfEnvFilesInAutoGeneratedDirsBacked() error {
	if !strings.Contains(s.cmdOutput, "0 file(s)") {
		return fmt.Errorf("expected '0 file(s)' backed up, got: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupUnitSteps) onlyAppsWebEnvLocalCopied() error {
	if !strings.Contains(s.cmdOutput, "1 file(s)") {
		return fmt.Errorf("expected '1 file(s)' backed up, got: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupUnitSteps) theEnvFileInsideNodeModulesNotBacked() error {
	// The mock result only contains .env.local, so node_modules/.env is never in output.
	if strings.Contains(s.cmdOutput, "node_modules") {
		return fmt.Errorf("expected node_modules/.env to be absent from output, got: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupUnitSteps) theEnvFileCopiedWithFlatStructure() error {
	return s.eachEnvFileCopiedPreservingRelativePath()
}

func (s *envBackupUnitSteps) theEnvFileCopiedUnderFeatureBranchSubdir() error {
	if !strings.Contains(s.cmdOutput, "feature-branch") {
		return fmt.Errorf("expected 'feature-branch' worktree in output, got: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupUnitSteps) theEnvFileCopiedUnderOpenShariaEnterpriseSubdir() error {
	if !strings.Contains(s.cmdOutput, "open-sharia-enterprise") {
		return fmt.Errorf("expected 'open-sharia-enterprise' worktree in output, got: %s", s.cmdOutput)
	}
	return nil
}

// --- Confirm Given steps ---

func (s *envBackupUnitSteps) theBackupDirAlreadyContainsBackedUpEnvFile() error {
	// Pre-existing file in backup triggers confirmation.
	// The mock envBackupFn will see ConfirmFn in opts.
	return nil
}

func (s *envBackupUnitSteps) theBackupDirIsEmpty() error {
	// No pre-existing files in backup.
	return nil
}

// --- Confirm When steps ---

func (s *envBackupUnitSteps) theDeveloperRunsEnvBackupAndConfirmsOverwrite() error {
	// Mock confirmFn to always confirm.
	confirmFn = func(_ io.Reader, _ io.Writer) func([]string) bool {
		return func(_ []string) bool { return true }
	}
	envBackupFn = func(opts envbackup.Options) (*envbackup.Result, error) {
		return &envbackup.Result{
			Direction: "backup",
			Dir:       opts.BackupDir,
			Files: []envbackup.FileEntry{
				{RelPath: ".env", AbsPath: "/mock-repo/.env", Size: 100},
			},
			Copied: 1,
		}, nil
	}
	return s.runEnvBackupCmd()
}

func (s *envBackupUnitSteps) theDeveloperRunsEnvBackupAndDeclinesOverwrite() error {
	envBackupFn = func(opts envbackup.Options) (*envbackup.Result, error) {
		return &envbackup.Result{
			Direction: "backup",
			Dir:       opts.BackupDir,
			Cancelled: true,
		}, nil
	}
	return s.runEnvBackupCmd()
}

func (s *envBackupUnitSteps) theDeveloperRunsEnvBackupWithForce() error {
	envBackupForce = true
	return s.runEnvBackupCmd()
}

// --- Confirm Then steps ---

func (s *envBackupUnitSteps) theEnvFileOverwrittenInBackupDir() error {
	if s.cmdErr != nil {
		return fmt.Errorf("expected success but got: %v", s.cmdErr)
	}
	return nil
}

func (s *envBackupUnitSteps) theOutputReportsBackupCancelled() error {
	if !strings.Contains(s.cmdOutput, "cancelled") {
		return fmt.Errorf("expected 'cancelled' in output, got: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupUnitSteps) theExistingBackupFileUnchanged() error {
	// When cancelled, no files should have been overwritten.
	// The mock returns Cancelled: true, so output should report cancelled.
	return nil
}

func (s *envBackupUnitSteps) theEnvFileOverwrittenWithoutPrompting() error {
	return s.theEnvFileOverwrittenInBackupDir()
}

func (s *envBackupUnitSteps) noConfirmationPromptShown() error {
	// Prompt is not shown when no conflicts exist. The mock succeeds normally.
	return nil
}

func (s *envBackupUnitSteps) theEnvFileCopiedToBackupDirConfirm() error {
	if !strings.Contains(s.cmdOutput, ".env") {
		return fmt.Errorf("expected '.env' in output, got: %s", s.cmdOutput)
	}
	return nil
}

// --- Config Given steps ---

func (s *envBackupUnitSteps) aGitRepoWithEnvFileAndClaudeConfig() error {
	envBackupFn = func(opts envbackup.Options) (*envbackup.Result, error) {
		files := []envbackup.FileEntry{
			{RelPath: ".env", AbsPath: "/mock-repo/.env", Size: 100, Source: "env"},
		}
		copied := 1
		if opts.IncludeConfig {
			files = append(files, envbackup.FileEntry{
				RelPath: ".claude/settings.local.json", AbsPath: "/mock-repo/.claude/settings.local.json", Size: 200, Source: "config",
			})
			copied = 2
		}
		return &envbackup.Result{
			Direction: "backup",
			Dir:       opts.BackupDir,
			Files:     files,
			Copied:    copied,
		}, nil
	}
	return nil
}

func (s *envBackupUnitSteps) aGitRepoWithEnvFileButNoKnownConfigFiles() error {
	envBackupFn = func(opts envbackup.Options) (*envbackup.Result, error) {
		return &envbackup.Result{
			Direction: "backup",
			Dir:       opts.BackupDir,
			Files: []envbackup.FileEntry{
				{RelPath: ".env", AbsPath: "/mock-repo/.env", Size: 100, Source: "env"},
			},
			Copied: 1,
		}, nil
	}
	return nil
}

// --- Config When steps ---

func (s *envBackupUnitSteps) theDeveloperRunsEnvBackupWithIncludeConfigForce() error {
	envBackupIncludeConfig = true
	envBackupForce = true
	return s.runEnvBackupCmd()
}

func (s *envBackupUnitSteps) theDeveloperRunsEnvBackupWithForceOnly() error {
	envBackupForce = true
	return s.runEnvBackupCmd()
}

// --- Config Then steps ---

func (s *envBackupUnitSteps) theClaudeConfigCopiedToBackupDir() error {
	if !strings.Contains(s.cmdOutput, ".claude/settings.local.json") {
		return fmt.Errorf("expected .claude/settings.local.json in output, got: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupUnitSteps) theClaudeConfigNotCopiedToBackupDir() error {
	if strings.Contains(s.cmdOutput, "settings.local.json") {
		return fmt.Errorf("expected .claude/settings.local.json to be absent from output, got: %s", s.cmdOutput)
	}
	return nil
}

func (s *envBackupUnitSteps) onlyTheEnvFileCopiedToBackupDir() error {
	if !strings.Contains(s.cmdOutput, "1 file(s)") {
		return fmt.Errorf("expected '1 file(s)' in output, got: %s", s.cmdOutput)
	}
	return nil
}

func TestUnitEnvBackup(t *testing.T) {
	s := &envBackupUnitSteps{}
	suite := godog.TestSuite{
		ScenarioInitializer: func(sc *godog.ScenarioContext) {
			sc.Before(s.before)
			sc.After(s.after)

			// Given steps.
			sc.Step(stepRepoWithEnvFilesAtRootAndSubdirs, s.aGitRepositoryContainingEnvFilesAtRootAndSubdirs)
			sc.Step(stepRepoWithEnvFileAtRoot, s.aGitRepositoryContainingAnEnvFileAtRoot)
			sc.Step(stepRepoWithSymlinkOversizedAndRegularEnvFile, s.aGitRepositoryContainingSymlinkOversizedAndRegularEnvFile)
			sc.Step(stepRepoWithNoEnvFiles, s.aGitRepositoryContainingNoEnvFiles)
			sc.Step(stepRepoWithEnvFilesInAutoGeneratedDirs, s.aGitRepositoryContainingEnvFilesInAutoGeneratedDirs)
			sc.Step(stepRepoWithNestedNodeModulesEnvAndLocalEnv, s.aGitRepositoryWhereAppsWebNodeModulesHasEnvAndAppsWebHasLocal)
			sc.Step(stepWorktreeWithEnvFileAtRoot, s.aGitWorktreeContainingEnvFileAtRoot)
			sc.Step(stepWorktreeNamedFeatureBranchWithEnvFile, s.aGitWorktreeNamedFeatureBranchWithEnvFile)
			sc.Step(stepMainRepoNamedOpenShariaEnterpriseWithEnv, s.theMainGitRepositoryNamedOpenShariaEnterpriseWithEnvFile)

			// When steps.
			sc.Step(stepDeveloperRunsEnvBackup, s.theDeveloperRunsEnvBackup)
			sc.Step(stepDeveloperRunsEnvBackupWithDirOutside, s.theDeveloperRunsEnvBackupWithDirOutside)
			sc.Step(stepDeveloperRunsEnvBackupWithDirInside, s.theDeveloperRunsEnvBackupWithDirInside)
			sc.Step(stepDeveloperRunsEnvBackupWithOutputJSON, s.theDeveloperRunsEnvBackupWithOutputJSON)
			sc.Step(stepDeveloperRunsEnvBackupWithWorktreeAware, s.theDeveloperRunsEnvBackupWithWorktreeAware)

			// Then steps.
			sc.Step(stepExitsSuccessfully, s.theCommandExitsSuccessfully)
			sc.Step(stepExitsWithFailure, s.theCommandExitsWithAFailureCode)
			sc.Step(stepEachEnvFileCopiedPreservingRelativePath, s.eachEnvFileCopiedPreservingRelativePath)
			sc.Step(stepOutputListsEachBackedUpFile, s.theOutputListsEachBackedUpFile)
			sc.Step(stepEnvFileCopiedToSpecifiedDirPreservingPath, s.theEnvFileCopiedToSpecifiedDirPreservingPath)
			sc.Step(stepOutputWarnsBackupDirMustBeOutside, s.theOutputWarnsBackupDirMustBeOutside)
			sc.Step(stepSymlinkedEnvFileSkippedWithWarning, s.theSymlinkedEnvFileSkippedWithWarning)
			sc.Step(stepOversizedEnvFileSkippedWithWarning, s.theOversizedEnvFileSkippedWithWarning)
			sc.Step(stepRegularEnvFileCopiedToBackupDir, s.theRegularEnvFileCopiedToBackupDir)
			sc.Step(stepOutputReportsZeroFilesBackedUp, s.theOutputReportsZeroFilesBackedUp)
			sc.Step(stepOutputIsValidJSON, s.theOutputIsValidJSON)
			sc.Step(stepJSONIncludesDirectionDirFilesCountsBackup, s.theJSONIncludesDirectionDirFilesCountsBackup)
			sc.Step(stepNoneOfEnvFilesInAutoGeneratedDirsBacked, s.noneOfEnvFilesInAutoGeneratedDirsBacked)
			sc.Step(stepOnlyAppsWebEnvLocalCopied, s.onlyAppsWebEnvLocalCopied)
			sc.Step(stepEnvFileInsideNodeModulesNotBacked, s.theEnvFileInsideNodeModulesNotBacked)
			sc.Step(stepEnvFileCopiedWithFlatStructure, s.theEnvFileCopiedWithFlatStructure)
			sc.Step(stepEnvFileCopiedUnderFeatureBranchSubdir, s.theEnvFileCopiedUnderFeatureBranchSubdir)
			sc.Step(stepEnvFileCopiedUnderOpenShariaEnterpriseSubdir, s.theEnvFileCopiedUnderOpenShariaEnterpriseSubdir)

			// Confirm scenario steps.
			sc.Step(stepBackupDirAlreadyContainsBackedUpEnvFile, s.theBackupDirAlreadyContainsBackedUpEnvFile)
			sc.Step(stepBackupDirIsEmpty, s.theBackupDirIsEmpty)
			sc.Step(stepDeveloperRunsEnvBackupAndConfirmsOverwrite, s.theDeveloperRunsEnvBackupAndConfirmsOverwrite)
			sc.Step(stepDeveloperRunsEnvBackupAndDeclinesOverwrite, s.theDeveloperRunsEnvBackupAndDeclinesOverwrite)
			sc.Step(stepDeveloperRunsEnvBackupWithForce, s.theDeveloperRunsEnvBackupWithForce)
			sc.Step(stepEnvFileOverwrittenInBackupDir, s.theEnvFileOverwrittenInBackupDir)
			sc.Step(stepOutputReportsBackupCancelled, s.theOutputReportsBackupCancelled)
			sc.Step(stepExistingBackupFileUnchanged, s.theExistingBackupFileUnchanged)
			sc.Step(stepEnvFileOverwrittenWithoutPrompting, s.theEnvFileOverwrittenWithoutPrompting)
			sc.Step(stepNoConfirmationPromptShown, s.noConfirmationPromptShown)
			sc.Step(stepEnvFileCopiedToBackupDir, s.theEnvFileCopiedToBackupDirConfirm)

			// Config scenario steps.
			sc.Step(stepRepoWithEnvFileAndClaudeConfig, s.aGitRepoWithEnvFileAndClaudeConfig)
			sc.Step(stepRepoWithEnvFileButNoKnownConfigFiles, s.aGitRepoWithEnvFileButNoKnownConfigFiles)
			sc.Step(stepDeveloperRunsEnvBackupWithIncludeConfigForce, s.theDeveloperRunsEnvBackupWithIncludeConfigForce)
			sc.Step(stepDeveloperRunsEnvBackupWithForceOnly, s.theDeveloperRunsEnvBackupWithForceOnly)
			sc.Step(stepClaudeConfigCopiedToBackupDir, s.theClaudeConfigCopiedToBackupDir)
			sc.Step(stepClaudeConfigNotCopiedToBackupDir, s.theClaudeConfigNotCopiedToBackupDir)
			sc.Step(stepOnlyEnvFileCopiedToBackupDir, s.onlyTheEnvFileCopiedToBackupDir)
		},
		Options: &godog.Options{
			Format:   "pretty",
			Paths:    []string{specsDirUnitEnvBackup},
			Tags:     "@env-backup,@env-backup-confirm,@env-backup-config",
			TestingT: t,
		},
	}
	if suite.Run() != 0 {
		t.Fatal("non-zero status returned, failed to run unit feature tests")
	}
}

// TestEnvBackupCmd_Initialization verifies the command metadata.
func TestEnvBackupCmd_Initialization(t *testing.T) {
	if envBackupCmd.Use != "backup" {
		t.Errorf("expected Use == %q, got %q", "backup", envBackupCmd.Use)
	}
	if !strings.Contains(strings.ToLower(envBackupCmd.Short), "back") {
		t.Errorf("expected Short to mention backup, got %q", envBackupCmd.Short)
	}
}

// TestEnvBackupCmd_NoArgs verifies the command accepts no positional arguments.
func TestEnvBackupCmd_NoArgs(t *testing.T) {
	if envBackupCmd.Args == nil {
		return // cobra.NoArgs is nil-able default; acceptable
	}
	if err := envBackupCmd.Args(envBackupCmd, []string{"unexpected"}); err == nil {
		t.Error("expected error when positional args provided, got nil")
	}
}

// TestEnvBackupCmd_ForceFlag verifies the --force flag is wired.
func TestEnvBackupCmd_ForceFlag(t *testing.T) {
	f := envBackupCmd.Flags().Lookup("force")
	if f == nil {
		t.Fatal("expected --force flag to be registered")
	}
	if f.Shorthand != "f" {
		t.Errorf("expected shorthand 'f', got %q", f.Shorthand)
	}
}

// TestEnvBackupCmd_IncludeConfigFlag verifies the --include-config flag is wired.
func TestEnvBackupCmd_IncludeConfigFlag(t *testing.T) {
	f := envBackupCmd.Flags().Lookup("include-config")
	if f == nil {
		t.Fatal("expected --include-config flag to be registered")
	}
}

// TestEnvBackupCmd_FnError verifies that errors from envBackupFn are propagated.
func TestEnvBackupCmd_FnError(t *testing.T) {
	original := envBackupFn
	defer func() { envBackupFn = original }()

	origGetwd := osGetwd
	origStat := osStat
	defer func() {
		osGetwd = origGetwd
		osStat = origStat
	}()

	osGetwd = func() (string, error) { return "/mock-repo", nil }
	osStat = func(name string) (os.FileInfo, error) {
		if name == "/mock-repo/.git" {
			return &mockFileInfo{name: ".git", isDir: true}, nil
		}
		return nil, os.ErrNotExist
	}

	envBackupFn = func(_ envbackup.Options) (*envbackup.Result, error) {
		return nil, fmt.Errorf("simulated backup failure")
	}

	origDir := envBackupDir
	defer func() { envBackupDir = origDir }()

	tmpBackup, err := os.MkdirTemp("", "env-backup-err-*")
	if err != nil {
		t.Fatalf("create temp dir: %v", err)
	}
	defer func() { _ = os.RemoveAll(tmpBackup) }()
	envBackupDir = tmpBackup

	buf := new(bytes.Buffer)
	envBackupCmd.SetOut(buf)
	envBackupCmd.SetErr(buf)
	cmdErr := envBackupCmd.RunE(envBackupCmd, []string{})
	if cmdErr == nil {
		t.Errorf("expected error from envBackupFn to propagate, got nil")
	}
}
