/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as RegisterImport } from "./routes/register";
import { Route as LoginImport } from "./routes/login";
import { Route as AuthenticatedImport } from "./routes/_authenticated";
import { Route as IndexImport } from "./routes/index";
import { Route as AuthenticatedTokensImport } from "./routes/_authenticated/tokens";
import { Route as AuthenticatedProfileImport } from "./routes/_authenticated/profile";
import { Route as AuthenticatedAdminImport } from "./routes/_authenticated/admin";
import { Route as AuthenticatedExpensesIndexImport } from "./routes/_authenticated/expenses/index";
import { Route as AuthenticatedExpensesSummaryImport } from "./routes/_authenticated/expenses/summary";
import { Route as AuthenticatedExpensesIdImport } from "./routes/_authenticated/expenses/$id";

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedRoute = AuthenticatedImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedTokensRoute = AuthenticatedTokensImport.update({
  id: "/tokens",
  path: "/tokens",
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthenticatedAdminRoute = AuthenticatedAdminImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthenticatedExpensesIndexRoute = AuthenticatedExpensesIndexImport.update({
  id: "/expenses/",
  path: "/expenses/",
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthenticatedExpensesSummaryRoute = AuthenticatedExpensesSummaryImport.update({
  id: "/expenses/summary",
  path: "/expenses/summary",
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthenticatedExpensesIdRoute = AuthenticatedExpensesIdImport.update({
  id: "/expenses/$id",
  path: "/expenses/$id",
  getParentRoute: () => AuthenticatedRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthenticatedImport;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterImport;
      parentRoute: typeof rootRoute;
    };
    "/_authenticated/admin": {
      id: "/_authenticated/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AuthenticatedAdminImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/profile": {
      id: "/_authenticated/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof AuthenticatedProfileImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/tokens": {
      id: "/_authenticated/tokens";
      path: "/tokens";
      fullPath: "/tokens";
      preLoaderRoute: typeof AuthenticatedTokensImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/expenses/$id": {
      id: "/_authenticated/expenses/$id";
      path: "/expenses/$id";
      fullPath: "/expenses/$id";
      preLoaderRoute: typeof AuthenticatedExpensesIdImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/expenses/summary": {
      id: "/_authenticated/expenses/summary";
      path: "/expenses/summary";
      fullPath: "/expenses/summary";
      preLoaderRoute: typeof AuthenticatedExpensesSummaryImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/expenses/": {
      id: "/_authenticated/expenses/";
      path: "/expenses";
      fullPath: "/expenses";
      preLoaderRoute: typeof AuthenticatedExpensesIndexImport;
      parentRoute: typeof AuthenticatedImport;
    };
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute;
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute;
  AuthenticatedTokensRoute: typeof AuthenticatedTokensRoute;
  AuthenticatedExpensesIdRoute: typeof AuthenticatedExpensesIdRoute;
  AuthenticatedExpensesSummaryRoute: typeof AuthenticatedExpensesSummaryRoute;
  AuthenticatedExpensesIndexRoute: typeof AuthenticatedExpensesIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTokensRoute: AuthenticatedTokensRoute,
  AuthenticatedExpensesIdRoute: AuthenticatedExpensesIdRoute,
  AuthenticatedExpensesSummaryRoute: AuthenticatedExpensesSummaryRoute,
  AuthenticatedExpensesIndexRoute: AuthenticatedExpensesIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(AuthenticatedRouteChildren);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/admin": typeof AuthenticatedAdminRoute;
  "/profile": typeof AuthenticatedProfileRoute;
  "/tokens": typeof AuthenticatedTokensRoute;
  "/expenses/$id": typeof AuthenticatedExpensesIdRoute;
  "/expenses/summary": typeof AuthenticatedExpensesSummaryRoute;
  "/expenses": typeof AuthenticatedExpensesIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/admin": typeof AuthenticatedAdminRoute;
  "/profile": typeof AuthenticatedProfileRoute;
  "/tokens": typeof AuthenticatedTokensRoute;
  "/expenses/$id": typeof AuthenticatedExpensesIdRoute;
  "/expenses/summary": typeof AuthenticatedExpensesSummaryRoute;
  "/expenses": typeof AuthenticatedExpensesIndexRoute;
}

export interface AllParams {
  "/_authenticated/expenses/$id": { id: string };
}

export interface FullSearchSchema extends Record<string, unknown> {
  registered?: string;
}

export type AllRouterInfo = {
  allParams: AllParams;
  fullSearchSchema: FullSearchSchema;
};

export interface AllRoutes {
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/_authenticated/admin": typeof AuthenticatedAdminRoute;
  "/_authenticated/profile": typeof AuthenticatedProfileRoute;
  "/_authenticated/tokens": typeof AuthenticatedTokensRoute;
  "/_authenticated/expenses/$id": typeof AuthenticatedExpensesIdRoute;
  "/_authenticated/expenses/summary": typeof AuthenticatedExpensesSummaryRoute;
  "/_authenticated/expenses/": typeof AuthenticatedExpensesIndexRoute;
}

export interface RoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/_authenticated/admin": typeof AuthenticatedAdminRoute;
  "/_authenticated/profile": typeof AuthenticatedProfileRoute;
  "/_authenticated/tokens": typeof AuthenticatedTokensRoute;
  "/_authenticated/expenses/$id": typeof AuthenticatedExpensesIdRoute;
  "/_authenticated/expenses/summary": typeof AuthenticatedExpensesSummaryRoute;
  "/_authenticated/expenses/": typeof AuthenticatedExpensesIndexRoute;
}

export interface RoutesByPath {
  "/": typeof IndexRoute;
  "": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/admin": typeof AuthenticatedAdminRoute;
  "/profile": typeof AuthenticatedProfileRoute;
  "/tokens": typeof AuthenticatedTokensRoute;
  "/expenses/$id": typeof AuthenticatedExpensesIdRoute;
  "/expenses/summary": typeof AuthenticatedExpensesSummaryRoute;
  "/expenses": typeof AuthenticatedExpensesIndexRoute;
}

export interface RouteIds {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/_authenticated/admin": typeof AuthenticatedAdminRoute;
  "/_authenticated/profile": typeof AuthenticatedProfileRoute;
  "/_authenticated/tokens": typeof AuthenticatedTokensRoute;
  "/_authenticated/expenses/$id": typeof AuthenticatedExpensesIdRoute;
  "/_authenticated/expenses/summary": typeof AuthenticatedExpensesSummaryRoute;
  "/_authenticated/expenses/": typeof AuthenticatedExpensesIndexRoute;
}

export interface RouteFullPaths {
  "/": "/";
  "/_authenticated": "";
  "/login": "/login";
  "/register": "/register";
  "/_authenticated/admin": "/admin";
  "/_authenticated/profile": "/profile";
  "/_authenticated/tokens": "/tokens";
  "/_authenticated/expenses/$id": "/expenses/$id";
  "/_authenticated/expenses/summary": "/expenses/summary";
  "/_authenticated/expenses/": "/expenses";
}

export interface RoutePaths {
  "/": "/";
  "": "";
  "/login": "/login";
  "/register": "/register";
  "/admin": "/admin";
  "/profile": "/profile";
  "/tokens": "/tokens";
  "/expenses/$id": "/expenses/$id";
  "/expenses/summary": "/expenses/summary";
  "/expenses": "/expenses";
}

export const routeTree = rootRoute
  ._addFileChildren([IndexRoute, AuthenticatedRouteWithChildren, LoginRoute, RegisterRoute])
  ._addFileTypes<FileRoutesByPath>();
