/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthenticatedTokensRouteImport } from "./routes/_authenticated/tokens";
import { Route as AuthenticatedProfileRouteImport } from "./routes/_authenticated/profile";
import { Route as AuthenticatedAdminRouteImport } from "./routes/_authenticated/admin";
import { Route as AuthenticatedExpensesIndexRouteImport } from "./routes/_authenticated/expenses/index";
import { Route as AuthenticatedExpensesSummaryRouteImport } from "./routes/_authenticated/expenses/summary";
import { Route as AuthenticatedExpensesIdRouteImport } from "./routes/_authenticated/expenses/$id";
import { Route as AuthenticatedExpensesNewRouteImport } from "./routes/_authenticated/expenses/new";

const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedTokensRoute = AuthenticatedTokensRouteImport.update({
  id: "/tokens",
  path: "/tokens",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedExpensesNewRoute = AuthenticatedExpensesNewRouteImport.update({
  id: "/expenses/new",
  path: "/expenses/new",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedExpensesIndexRoute = AuthenticatedExpensesIndexRouteImport.update({
  id: "/expenses/",
  path: "/expenses/",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedExpensesSummaryRoute = AuthenticatedExpensesSummaryRouteImport.update({
  id: "/expenses/summary",
  path: "/expenses/summary",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedExpensesIdRoute = AuthenticatedExpensesIdRouteImport.update({
  id: "/expenses/$id",
  path: "/expenses/$id",
  getParentRoute: () => AuthenticatedRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/admin": typeof AuthenticatedAdminRoute;
  "/profile": typeof AuthenticatedProfileRoute;
  "/tokens": typeof AuthenticatedTokensRoute;
  "/expenses/$id": typeof AuthenticatedExpensesIdRoute;
  "/expenses/summary": typeof AuthenticatedExpensesSummaryRoute;
  "/expenses/new": typeof AuthenticatedExpensesNewRoute;
  "/expenses/": typeof AuthenticatedExpensesIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/admin": typeof AuthenticatedAdminRoute;
  "/profile": typeof AuthenticatedProfileRoute;
  "/tokens": typeof AuthenticatedTokensRoute;
  "/expenses/$id": typeof AuthenticatedExpensesIdRoute;
  "/expenses/summary": typeof AuthenticatedExpensesSummaryRoute;
  "/expenses/new": typeof AuthenticatedExpensesNewRoute;
  "/expenses": typeof AuthenticatedExpensesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/_authenticated/admin": typeof AuthenticatedAdminRoute;
  "/_authenticated/profile": typeof AuthenticatedProfileRoute;
  "/_authenticated/tokens": typeof AuthenticatedTokensRoute;
  "/_authenticated/expenses/$id": typeof AuthenticatedExpensesIdRoute;
  "/_authenticated/expenses/summary": typeof AuthenticatedExpensesSummaryRoute;
  "/_authenticated/expenses/new": typeof AuthenticatedExpensesNewRoute;
  "/_authenticated/expenses/": typeof AuthenticatedExpensesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/register"
    | "/admin"
    | "/profile"
    | "/tokens"
    | "/expenses/$id"
    | "/expenses/summary"
    | "/expenses/new"
    | "/expenses/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/register"
    | "/admin"
    | "/profile"
    | "/tokens"
    | "/expenses/$id"
    | "/expenses/summary"
    | "/expenses/new"
    | "/expenses";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/login"
    | "/register"
    | "/_authenticated/admin"
    | "/_authenticated/profile"
    | "/_authenticated/tokens"
    | "/_authenticated/expenses/$id"
    | "/_authenticated/expenses/summary"
    | "/_authenticated/expenses/new"
    | "/_authenticated/expenses/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/tokens": {
      id: "/_authenticated/tokens";
      path: "/tokens";
      fullPath: "/tokens";
      preLoaderRoute: typeof AuthenticatedTokensRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/profile": {
      id: "/_authenticated/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof AuthenticatedProfileRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/admin": {
      id: "/_authenticated/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AuthenticatedAdminRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/expenses/": {
      id: "/_authenticated/expenses/";
      path: "/expenses";
      fullPath: "/expenses/";
      preLoaderRoute: typeof AuthenticatedExpensesIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/expenses/summary": {
      id: "/_authenticated/expenses/summary";
      path: "/expenses/summary";
      fullPath: "/expenses/summary";
      preLoaderRoute: typeof AuthenticatedExpensesSummaryRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/expenses/$id": {
      id: "/_authenticated/expenses/$id";
      path: "/expenses/$id";
      fullPath: "/expenses/$id";
      preLoaderRoute: typeof AuthenticatedExpensesIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/expenses/new": {
      id: "/_authenticated/expenses/new";
      path: "/expenses/new";
      fullPath: "/expenses/new";
      preLoaderRoute: typeof AuthenticatedExpensesNewRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute;
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute;
  AuthenticatedTokensRoute: typeof AuthenticatedTokensRoute;
  AuthenticatedExpensesIdRoute: typeof AuthenticatedExpensesIdRoute;
  AuthenticatedExpensesSummaryRoute: typeof AuthenticatedExpensesSummaryRoute;
  AuthenticatedExpensesNewRoute: typeof AuthenticatedExpensesNewRoute;
  AuthenticatedExpensesIndexRoute: typeof AuthenticatedExpensesIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTokensRoute: AuthenticatedTokensRoute,
  AuthenticatedExpensesIdRoute: AuthenticatedExpensesIdRoute,
  AuthenticatedExpensesSummaryRoute: AuthenticatedExpensesSummaryRoute,
  AuthenticatedExpensesNewRoute: AuthenticatedExpensesNewRoute,
  AuthenticatedExpensesIndexRoute: AuthenticatedExpensesIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(AuthenticatedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
