name: ayokoding-www-test-local-deploy-prod

on:
  schedule:
    - cron: "0 23 * * *" # 6 AM WIB (UTC+7)
    - cron: "0 11 * * *" # 6 PM WIB (UTC+7)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test-local-deploy-prod:
    uses: ./.github/workflows/_reusable-www-test-local-deploy.yml
    with:
      app-name: ayokoding-www
      prod-branch: prod-ayokoding-www
      health-url: http://localhost:3101/api/trpc/meta.health
      health-timeout: 150
      copy-prerender-manifest-for-e2e: true
      stop-docker-before-fe-e2e: true
