name: Test and Deploy - OSE Platform Web

on:
  schedule:
    - cron: "0 23 * * *" # 6 AM WIB (UTC+7)
    - cron: "0 11 * * *" # 6 PM WIB (UTC+7)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-and-deploy:
    uses: ./.github/workflows/_reusable-test-and-deploy.yml
    with:
      app-name: oseplatform-web
      prod-branch: prod-oseplatform-web
      health-url: http://localhost:3100/api/trpc/meta.health
      health-timeout: 150
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
